name: wx天气预报推送

on:
  schedule:
    # 启动时间，为 UTC 时间对应北京时间早7点05分
    - cron: '05 23 * * *'
    # 启动时间，为 UTC 时间对应北京时间下午5点30分
    - cron: '30 09 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Say hello to your girlfriend every day

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          pip-${{ runner.os }}-

    - name: Install pip
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run weather
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        USER_IDS: ${{ secrets.USER_IDS }}
      run: |
        echo "APP_KEY: $APP_KEY"
        echo "USER_IDS: $USER_IDS"
        python main.py || echo "任务失败，请检查日志"
